### ISSUE TITLE
[Question] How to retrieve dao header field from L1?

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/lumos#504]
As per title, I'm wondering: within a Lumos script, what's the most idiomatic way to retrieve dao header field from Nervos L1?

I'm asking here since GitHub issues are SEO friendly and very likely in the future there will be other L1 developers wondering the same :wink:

Phroi

**Comment by phroi** [comment]
My [current non-solution](https://github.com/ickb/v1-bot-demo/blob/d3e54f235eb46b812c235fb7f59dd8ff523ace52/1_deposit_into_ickb/index.js#L129) is something along the lines of:

```
import { RPC } from "@ckb-lumos/rpc";
import pkg from '@ckb-lumos/base';
const { Header } = pkg;

const rpc = new RPC("http://localhost:8114", indexer);
const serializedHeader = await rpc.get_header(receiptOutPoint.txHash);
const header = new Header(serializedHeader);
```
It's a non-solution because executing it throws this error:


> file:///home/user/v1-bot-demo/1_deposit_into_ickb/index.js:129
> 	const serializedHeader = await rpc.get_header(receiptOutPoint.txHash);
> 	                                   ^
> 
> TypeError: rpc.get_header is not a function
>     at depositPhaseTwo (file:///home/user/v1-bot-demo/1_deposit_into_ickb/index.js:129:37)
>     at main (file:///home/user/v1-bot-demo/1_deposit_into_ickb/index.js:215:8)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by homura** [comment]
hi, `lumos@0.19` has a breaking change which changes the snake case API to camel case, maybe we can follow the [migration guide](https://lumos-website.vercel.app/migrations/migrate-to-v0.19#step-1---codemod) to upgrade the outdated code

**Comment by phroi** [comment]
Why the [0.19 documentation on rpc](https://lumos-website-git-stable-cryptape.vercel.app/api/classes/rpc.rpc-1.html#get_header) shows the snake case method?

**Comment by phroi** [comment]
That fixed the issue with `getHeader`, thanks a lot @homura!!

Now, what's the correct way to import `Header` from `@ckb-lumos/base`?

**Comment by homura** [comment]
> Why the [0.19 documentation on rpc](https://lumos-website-git-stable-cryptape.vercel.app/api/classes/rpc.rpc-1.html#get_header) shows the snake case method?

Sorry, just realized the document is out of date, thanks for figured it out, we'll update the docs

> Now, what's the correct way to import Header from @ckb-lumos/base?

The [`get_header`](https://github.com/nervosnetwork/ckb/blob/develop/rpc/README.md#method-get_header) RPC returns a deserialized `Header`, so we don't need to deserialize it again. 

BTW, if we want to (de)serialize something in the `blockchain.mol`, we can

```
import { blockchain } from "@ckb-lumos/base"

// serialize
blockchain.Header.pack({...})

// deserialize
blockchain.Header.unpack('0x...')
```

**Comment by phroi** [comment]
> thanks for figured it out, we'll update the docs

Glad to be of help :pray:

> RPC returns a deserialized Header, so we don't need to deserialize it again

I still have a strange issue: the returned header is **null**.

Right now [my code](https://github.com/ickb/v1-bot-demo/blob/45da9513180ec758b861aa03cdb00dba9185b2e5/1_deposit_into_ickb/index.js#L130) looks like this:

```
console.log("DEPOSIT PHASE ONE\n");

[...]

console.log("DEPOSIT PHASE TWO\n");

await new Promise(r => setTimeout(r, 60000));

const rpc = new RPC("http://localhost:8114", indexer);
const txHash = receiptOutPoint.txHash;
console.log("Fetch header using Tx Hash:", txHash)
const header = await rpc.getHeader(txHash);
console.log("Header:", header);
console.log("Header DAO:", header.dao);
return
```

The output I get is:
```
DEPOSIT PHASE ONE

Cell Deps:
  - depType: depGroup
    outPoint: 0xdcbeaaf5dbe657856d408e23517c1869d68427d9b9d50ac06012a59ce51bcd0e-0x0
  - depType: code
    outPoint: 0xe01a0f2147f0b6b7e2439d4b61f15d0795d78cce4ba0d3aeefe979be78d7c461-0x2
  - depType: code
    outPoint: 0xfc6e784882ee88671ff89e1b460037464476ae740d26288f15c7807d0417ad7f-0x1
Inputs:
  - capacity: 10,000,000,000,000 Shannons (100,000.0000 CKBytes)
    lock: 0x6ee8b1ea3db94183c5e5a47fbe82110101f6f8d3e18d1ecd4d6a5425e648da69
    type: null
    outPoint: 0x94b13b8f319ae499fc36887747122894a7166714318fc36d5c1903661c90c31b-0x0
  - capacity: 10,000,000,000,000 Shannons (100,000.0000 CKBytes)
    lock: 0x6ee8b1ea3db94183c5e5a47fbe82110101f6f8d3e18d1ecd4d6a5425e648da69
    type: null
    outPoint: 0x94b13b8f319ae499fc36887747122894a7166714318fc36d5c1903661c90c31b-0x1
Outputs:
  - capacity: 10,008,200,000,000 Shannons (100,082.0000 CKBytes)
    lock: 0x585712302fcd449ba6585453e45b90f2d93de76e7105659b36661bb1a3f95c89
    type: 0xcc77c4deac05d68ab5b26828f0bf4565a8d73113d7bb7e92b8362b8a74e58e58
  - capacity: 10,200,000,000 Shannons (102.0000 CKBytes)
    lock: 0x6ee8b1ea3db94183c5e5a47fbe82110101f6f8d3e18d1ecd4d6a5425e648da69
    type: 0x585712302fcd449ba6585453e45b90f2d93de76e7105659b36661bb1a3f95c89
  - capacity: 9,981,599,900,000 Shannons (99,815.9990 CKBytes)
    lock: 0x6ee8b1ea3db94183c5e5a47fbe82110101f6f8d3e18d1ecd4d6a5425e648da69
    type: null
TX Fee: 100,000 Shannons

Transaction Sent: 0x444a50e7f7de707ded2ecad97f02b2a4e67f83edf504faf6bc95c88ceefb9ce1

Waiting for transaction to confirm.....

DEPOSIT PHASE TWO

Fetch header using Tx Hash: 0x444a50e7f7de707ded2ecad97f02b2a4e67f83edf504faf6bc95c88ceefb9ce1
Header: null
file:///home/user/v1-bot-demo/1_deposit_into_ickb/index.js:132
	console.log("Header DAO:", header.dao);
	                                  ^

TypeError: Cannot read properties of null (reading 'dao')
    at depositPhaseTwo (file:///home/user/v1-bot-demo/1_deposit_into_ickb/index.js:132:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///home/user/v1-bot-demo/1_deposit_into_ickb/index.js:218:2)
```
